### PR TITLE
Remove polyfill and point to new archived location

### LINKED ISSUE #433: How about we move the polyfill out?
It might be good to move the polyfill out... then it makes it easier for us to manage spec issues and polyfill issues.

### PR DESCRIPTION
**Pull request by miketaylr**
Closes #433

### CODE REVIEW

**Comment by miketaylr** [comment]
cc @szager-chromium @emilio

**Review by emilio — APPROVED** [review]

**Comment by emilio** [comment]
Ah, I just saw you wanted review from @philipwalton, lmk if you want to revert this change and wait for that.

**Comment by philipwalton** [comment]
> Ah, I just saw you wanted review from @philipwalton, lmk if you want to revert this change and wait for that.

No worries. LGTM!

**Comment by miketaylr** [comment]
thanks both!

**Pull request merged**
