### PR TITLE
Specifying visual viewport for root intersection rect and clarifying …

### PR DESCRIPTION
**Pull request by ChumpChief**
…coordinate space for rootMargin

This PR corresponds to issue #95 @szager-chromium @bokand @RByers

### CODE REVIEW

**Comment by mpb** [comment]
LGTM

**Comment by ChumpChief** [comment]
When can this be merged?  Anything else you need from me to help get this in?

**Comment by szager-chromium** [comment]
I'd prefer it if we could define the option to select layout vs. visual viewport at the same time as we change the language, and the language should probably use "visual or layout viewport" as appropriate.

**Comment by ChumpChief** [comment]
Can we treat that as a separate, augmenting change following this one up?  I think the addition of an option probably needs more discussion (e.g. see my and David's comments on #95) and I don't think it results in any change to the default behavior, which is what this issue/PR is focused on.

**Comment by yoavweiss** [comment]
@ChumpChief - Apologies for letting this slide for so long, but could you join the WICG in order to appease the IPR bots?

**Comment by siusin** [comment]
Please merge the requested change to the `master` branch (`index.bs`) once the group/editors reach a consensus on this issue, the travis bot will generate an` index.html` with the latest version of Bikeshed and push it to [`gh-pages`](https://w3c.github.io/IntersectionObserver/).

Our apologies for the inconvenience.

**Comment by yoavweiss** [comment]
@ChumpChief - friendly ping :) Can you join the WICG so the IPR bots would be happy and green?

**Comment by ChumpChief** [comment]
Wow, old one :)  I think I've linked it now, let me know if there's still any issue.

**Comment by yoavweiss** [comment]
@ChumpChief Yeah, dug it from the bottom of my inbox... :D repo-manager is still not happy. Not sure why

**Comment by siusin** [comment]
@ChumpChief could you try [linking your Github account with your W3C account](https://www.w3.org/users/myprofile/connectedaccounts)? Also, please remove the .html file from this pull request? the .travis bot will generate the document for you once you submit the .bs file :)

(Thanks @yoavweiss ;)

**Comment by ChumpChief** [comment]
I linked it yesterday as noted.  Shows up correctly on the connectedaccounts page as well.

**Comment by siusin** [comment]
Thanks for the update @ChumpChief .

@dontcallmedom the IRP checker reported an error when we tried to revalidate a PR after migrating the repo from WICG... any suggestion?

> Unknown repository: WICG/IntersectionObserver

**Comment by dontcallmedom** [comment]
@siusin fixed - at the moment, the [IPR checker doesn't handle correctly handling of existing Pull Requests after migration of a repo](https://github.com/w3c/ash-nazg/issues/64#issuecomment-355912881), so this has to be fixed manually.

**Comment by siusin** [comment]
Thanks @dontcallmedom !

**Comment by ChumpChief** [comment]
@yoavweiss Looking to wrap this one up -- anything you need me to do?

**Pull request closed without merging**
